### ISSUE TITLE
Compilation Error: size Not Found in Scope in main.rs

### ISSUE THREAD

**Issue by IndigoNakamoto** [nicolas-siplis/moonbird#2]
While compiling the moonbird Rust project using the command cargo build --release, a compilation error occurred due to an unresolved reference to a size variable. The error message suggests that the size variable isn't found in the current scope. The detailed error message is:

error[E0425]: cannot find value `size` in this scope
   --> src/main.rs:219:25
    |
219 |             for _ in 0..size {
    |                         ^^^^ not found in this scope
    |
help: you might have meant to write `.` instead of `..`
    |
219 -             for _ in 0..size {
219 +             for _ in 0.size {
    |

**Comment by Chiplis** [comment]
Just pushed a fix for the compilation error, thanks for the heads up! I'm closing this issue but if anything else pops up please feel free to open up another one.
