### ISSUE TITLE
It seems not working now

### ISSUE THREAD

**Issue by jhyoonco** [nicolas-siplis/moonbird#4]
Sorry for my bad English in advance I'm not an English speaker.
When I try to download a space there shows an error like below.
```Error: error decoding response body: EOF while parsing a value at line 1 column 0```
I don't know about twitter api at all but it seems the 'AudioSpaceById' api doesn't work now.
It worked before (a few weeks ago?)

**Comment by Chiplis** [comment]
Hi there!

Yep, unfortunately it looks like Twitter has disabled the bearer token I replaced a few weeks ago. I don't know if there's a way to get a bearer token for your personal account, but if that's possible then you should be able to use it to keep Moonbird working.

**Comment by jhyoonco** [comment]
Thank you for your reply. I see, it seems better search a way to get bearer token from personal account.
